[project]
name = "trip-planner-hackathon"
version = "0.5.2"
description = "Flask based app for trip planning with GenAI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "google>=3.0.0",
    "google-generativeai>=0.8.5",
]

